---
- name: BGP Summary junos
  hosts: "{{ survey_ip }}"
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars_files: vars/main.yml
  tasks:
    - name: show bgp
      ansible.netcommon.cli_command:
        command: "show bgp summary | no-more"
      register: result

    - name: debug
      debug:
        var: result.stdout_lines
